#!/usr/bin/env python3
"""Render the Deviations tables of the manuscripts from docs/manuscripts/deviations.yaml.

Writes paper1/deviations_table.tex (Paper 1 rows 14-31) and paper2/deviations_table.tex
(Paper 2 rows 1-3). Each file is a longtable body only; the manuscripts \\input{} it.
Run from anywhere: paths are resolved relative to this script. No result is invented here:
the YAML is a transcript of the pre-registration Deviations tables.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import pathlib
import re
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
YAML = ROOT / "deviations.yaml"

_ESC = {
    "&": r"\&", "%": r"\%", "#": r"\#", "_": r"\_",
    "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
}


def tex_escape(s: str) -> str:
    """Escape LaTeX specials outside $...$ math; text inside $...$ is passed through verbatim.

    YAML content may therefore carry inline math such as $p^4/9$ or $\\|t\\|$; everything else is plain text.
    """
    parts = s.split("$")
    if len(parts) % 2 == 0:
        raise ValueError(f"unbalanced $ in: {s!r}")
    out = []
    for i, part in enumerate(parts):
        if i % 2 == 1:
            out.append("$" + part + "$")
        else:
            out.append("".join(_ESC.get(c, c) for c in part))
    return "".join(out)


def render(rows: list[dict], caption: str, label: str, source: str) -> str:
    lines = [
        "% Auto-generated by scripts/build_deviations_table.py from deviations.yaml on "
        + _dt.date.today().isoformat() + ". Do not edit by hand.",
        r"\begin{longtable}{@{}p{0.05\linewidth}p{0.11\linewidth}p{0.20\linewidth}p{0.42\linewidth}p{0.16\linewidth}@{}}",
        r"\caption{" + tex_escape(caption) + r" Source: " + tex_escape(source) + r".}\label{" + label + r"}\\",
        r"\toprule",
        r"No. & Date & Title & Content & Approval \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"No. & Date & Title & Content & Approval \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]
    for r in rows:
        lines.append(
            f"{r['number']} & {r['date']} & {tex_escape(str(r['title']))} & "
            f"{tex_escape(str(r['content']))} & {tex_escape(str(r['approval']))} \\\\"
        )
    lines.append(r"\end{longtable}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--yaml", default=str(YAML))
    ap.add_argument("--check", action="store_true", help="validate the YAML and exit without writing")
    a = ap.parse_args()
    data = yaml.safe_load(pathlib.Path(a.yaml).read_text())
    outputs = {
        "paper1": (ROOT / "paper1" / "deviations_table.tex",
                   "Deviations from the signed Paper 1 pre-registration recorded before any hardware minute (rows 14--31; rows 1--13 are the citation corrections of v0.2).",
                   "tab:deviations"),
        "paper2": (ROOT / "paper2" / "deviations_table.tex",
                   "Deviations from the Paper 2 pre-registration (rows 1--3).",
                   "tab:deviations"),
    }
    for key, (path, caption, label) in outputs.items():
        block = data.get(key)
        if not block or "rows" not in block:
            sys.exit(f"deviations.yaml: missing '{key}.rows'")
        rows = block["rows"]
        nums = [r["number"] for r in rows]
        if nums != sorted(nums) or len(set(nums)) != len(nums):
            sys.exit(f"deviations.yaml: {key} rows must be unique and ascending, got {nums}")
        for r in rows:
            for field in ("number", "date", "title", "content", "approval"):
                if field not in r:
                    sys.exit(f"deviations.yaml: {key} row {r.get('number')} lacks '{field}'")
        if a.check:
            print(f"{key}: {len(rows)} rows ok ({nums[0]}..{nums[-1]})")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(rows, caption, label, block.get("source", "")))
        print(f"wrote {path.relative_to(ROOT)} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
